### ISSUE TITLE
Inconsistent Theme Toggling During GitHub User Search

### ISSUE THREAD

**Issue by 0ME9A** [0ME9A/devFinder#18]
## Issue: Inconsistent Theme Toggling During GitHub User Search

Description:
Currently, the devFinder website exhibits inconsistent behaviour with theme toggling when a user performs a search for a GitHub user. Upon each search action, the theme automatically toggles between dark and light modes, causing confusion and disrupting the user experience.

Steps to Reproduce:

Visit the devFinder website.
Perform a search for a GitHub user.
Note that the theme toggles between dark and light modes unexpectedly.
Expected Behavior:
The theme should maintain its state consistently regardless of user actions such as searching for a GitHub user. The theme preference chosen by the user should persist throughout the browsing session without unexpected toggling.

Additional Information:
Inconsistent theme toggling can lead to user confusion and disrupt the overall browsing experience. Addressing this issue will contribute to a smoother and more predictable user interaction with the devFinder website.

**Comment by taiyou1116** [comment]
https://github.com/0ME9A/devFinder/pull/21

Hello! nice to meet you.
Verification please😄
